version: 0.2
env:
  variables:
    BUCKET_NAME: "oening-serverless-environment"
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket $BUCKET_NAME --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - outputSamTemplate.yaml
