AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  Test:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.6
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any